import { Router } from "express";
import routesCourt from "../modules/courts/court.routes.js";
import routesBookings from "../modules/bookings/booking.routes.js";
import authRouter from "../modules/auth/auth.route.js";
import routesInvoices from "../modules/invoices/invoice.routes.js";
import routerPayment from "../modules/payment/payment.routes.js";
import routesEquipment from "../modules/equipments/equipment.routes.js";
import routesBookingItem from "../modules/bookingItems/bookingItem.routes.js";
import userRouter from "../modules/users/user.routes.js";
import uploadRoutes from "../common/routes/upload.routes.js";
import voucherRoutes from "../modules/vouchers/voucher.routes.js";
import routesReport from "../modules/reports/report.routes.js";
import routerReview from "../modules/review/review.routes.js";
import contactRouter from "../modules/contacts/contact.routes.js";
const routes = Router();

routes.use("/courts", routesCourt);
routes.use("/bookings", routesBookings);
routes.use("/auth", authRouter);
routes.use("/invoices", routesInvoices);
routes.use("/payment", routerPayment);
routes.use("/equipments", routesEquipment);
routes.use("/booking-items", routesBookingItem);
routes.use("/users", userRouter);
routes.use("/upload", uploadRoutes);
routes.use("/vouchers", voucherRoutes);
routes.use("/review", routerReview);
routes.use("/reports", routesReport);
routes.use("/contacts", contactRouter);
export default routes;
