import dotenv from "dotenv";

dotenv.config({});

const {
  HOST: ENV_HOST = "localhost",
  DB_URI,
  PORT: ENV_PORT = 3000,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  JWT_ACCESS_EXPIRED,
  JWT_ACCESS_SECRECT,
  FONT_END_URL,
  FRONTEND_URL,
  FRONT_END_URL: FRONT_END_URL_ALT,
  EMAIL,
  EMAIL_PASSWORD: EMAIL_PASSWORD_RAW,
  BACKEND_URL,
  VNPAY_TMN_CODE: VNPAY_TMN_CODE_RAW,
  VNPAY_HASH_SECRET: VNPAY_HASH_SECRET_RAW,
  VNPAY_RETURN_URL: VNPAY_RETURN_URL_RAW,
  VNPAY_IPN_URL: VNPAY_IPN_URL_RAW,
  VNPAY_PAYMENT_URL: VNPAY_PAYMENT_URL_RAW,
  VNP_TMN_CODE,
  VNP_HASH_SECRET,
  VNP_URL,
  VNP_RETURN_URL_SUCCESS,
  VNP_RETURN_URL_CANCEL,
} = process.env;

export const HOST = ENV_HOST;
export const PORT = ENV_PORT;

// Xử lý EMAIL_PASSWORD - loại bỏ khoảng trắng nếu có (App Password Gmail)
const EMAIL_PASSWORD = EMAIL_PASSWORD_RAW ? EMAIL_PASSWORD_RAW.replace(/\s+/g, '') : EMAIL_PASSWORD_RAW;

export {
  DB_URI,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  JWT_ACCESS_EXPIRED,
  JWT_ACCESS_SECRECT,
  EMAIL,
  EMAIL_PASSWORD,
};

const FRONTEND_FALLBACK =
  FRONTEND_URL || FRONT_END_URL_ALT || FONT_END_URL || "http://localhost:5173";
export const FRONT_END_URL = FRONTEND_FALLBACK;

const BACKEND_BASE_URL =
  BACKEND_URL || `http://${HOST}:${PORT}`;

export const VNPAY_TMN_CODE =
  VNPAY_TMN_CODE_RAW || VNP_TMN_CODE || "";
export const VNPAY_HASH_SECRET =
  VNPAY_HASH_SECRET_RAW || VNP_HASH_SECRET || "";
export const VNPAY_PAYMENT_URL =
  VNPAY_PAYMENT_URL_RAW || VNP_URL || "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html";
export const VNPAY_RETURN_URL =
  VNPAY_RETURN_URL_RAW || `${BACKEND_BASE_URL}/api/payments/vnpay/return`;
export const VNPAY_IPN_URL =
  VNPAY_IPN_URL_RAW || `${BACKEND_BASE_URL}/api/payments/vnpay/ipn`;

export const VNPAY_SUCCESS_REDIRECT =
  VNP_RETURN_URL_SUCCESS || `${FRONT_END_URL}/payment/result`;
export const VNPAY_CANCEL_REDIRECT =
  VNP_RETURN_URL_CANCEL || VNPAY_SUCCESS_REDIRECT;
